version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "9091:9091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task  # Banco de dados do outro docker-compose
      SPRING_DATASOURCE_USERNAME: task
      SPRING_DATASOURCE_PASSWORD: task
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:29092
    networks:
      - task-producer_broker-kafka  # Rede Kafka compartilhada
      - app-network  # Rede do banco de dados compartilhada

networks:
  task-producer_broker-kafka:
    external: true  # Rede externa compartilhada para Kafka

  app-network:
    external: true  # Rede externa compartilhada para o banco de dados
